name: Integration Testing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  IntegrationTesting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - uses: isbang/compose-action@v1.4.1
    - name: check license
      shell: bash
      run: |
        id
        free -mm
        cat /proc/cpuinfo
        docker --version
        docker-compose --version

    #- name: Build all-in-one
    #  run: sh ./scripts/all-in-one/build.sh
